// English dictionary — simple, concrete, phonetically distinct nouns.
// Curated: no homophones, no confusable near-pairs (enforced by tests/dictionaries.test.mjs).
export const WORDS_EN = [
  // animals
  "dog", "frog", "kitten", "pony", "cow", "pig", "goose", "swan", "eagle",
  "rabbit", "hamster", "squirrel", "wolf", "bear", "lion", "tiger",
  "elephant", "giraffe", "zebra", "gorilla", "monkey", "camel", "dolphin",
  "whale", "shark", "octopus", "crab", "shrimp", "penguin", "turtle",
  "snake", "spider", "bee", "wasp", "butterfly", "beetle",
  "ladybug", "hedgehog", "pigeon", "seagull", "flamingo", "peacock",
  "rooster", "ostrich", "koala", "panda", "kangaroo", "raccoon", "beaver",
  "walrus", "unicorn", "dragon", "dinosaur", "crocodile", "iguana",
  "jaguar", "leopard", "lobster", "oyster", "pelican", "reindeer",
  "salamander", "scorpion", "seahorse", "snail", "squid", "toucan",
  "mammoth", "hippo", "rhino", "jellyfish", "grasshopper", "chipmunk",
  "gazelle", "falcon", "woodpecker", "hummingbird", "caterpillar",
  "goldfish", "salmon", "tuna", "cheetah", "panther", "sloth", "gecko",
  "orca", "starfish", "armadillo", "buffalo", "llama", "porcupine", "skunk",
  // food
  "apple", "banana", "orange", "lemon", "grape", "cherry", "peach", "mango",
  "melon", "watermelon", "coconut", "strawberry", "raspberry", "blueberry",
  "pineapple", "carrot", "potato", "tomato", "onion", "garlic",   "bread", "cheese", "butter", "honey", "sugar", "milk", "coffee", "juice",
  "water", "soup", "salad", "rice", "pizza", "sandwich", "cookie", "candy",
  "chocolate", "egg", "bacon", "chicken", "pancake", "waffle", "muffin",
  "pretzel", "popcorn", "peanut", "walnut", "almond", "olive", "avocado",
  "lettuce", "spinach", "broccoli", "cabbage", "cucumber", "pumpkin",
  "mushroom", "noodle", "spaghetti", "hamburger", "sausage", "mustard",
  "ketchup", "syrup", "vanilla", "cinnamon", "pickle", "radish",
  "raisin", "cereal", "yogurt", "lemonade", "grapefruit", "papaya",
  "pudding", "sushi", "taco", "kiwi", "apricot",
  // body
  "face", "tooth", "mouth", "finger", "thumb", "foot", "heart", "elbow",
  "skeleton",
  // house & objects
  "house", "door", "window", "roof", "brick", "ladder", "chimney", "mirror",
  "pillow", "blanket", "sofa", "chair", "table", "closet", "shelf", "lamp",
  "candle", "clock", "phone", "radio", "oven", "pot", "plate",
  "cup", "fork", "knife", "bottle", "basket", "broom", "towel", "brush",
  "scissors", "needle", "button", "suitcase", "backpack", "box", "gift",
  "book", "newspaper", "envelope", "pencil", "paper", "notebook", "crayon",
  "carpet", "curtain", "kettle", "teapot", "microwave", "sponge", "bathtub",
  "toothbrush", "mattress", "flashlight", "magnet", "camera", "computer",
  "wallet", "coin", "medal", "trophy", "ribbon", "doll", "puzzle", "kite",
  "balloon", "whistle", "drum", "guitar", "piano", "violin", "flute",
  "trumpet", "harp", "harmonica", "saxophone", "tambourine", "xylophone",
  "accordion", "bell", "hammer", "drill", "shovel", "rope",   "anchor", "compass", "map", "flag", "tent", "umbrella", "mask", "helmet",
  "sword", "shield", "arrow", "treasure", "crown", "statue", "mailbox",
  "toolbox", "wheelbarrow", "hammock", "telescope", "microscope",
  "microphone", "headphones", "glasses", "necklace", "bracelet", "pearl",
  "diamond", "emerald", "marble", "feather", "nest", "seashell", "perfume",
  "photo", "ticket", "barrel", "bubble", "calendar", "chess", "fireworks",
  "fossil", "napkin", "parachute", "raft", "paddle", "surfboard", "ukulele",
  "yacht", "motorcycle", "binoculars", "hourglass", "padlock", "acorn",
  "antenna", "ambulance", "honeycomb", "haystack", "zipper", "apron",
  // nature
  "sun", "moon", "star", "sky", "cloud", "snow", "storm", "thunder",
  "rainbow", "wind", "mountain", "hill", "valley", "river", "lake", "ocean",
  "sand", "island", "volcano", "cave", "forest", "jungle", "desert",
  "meadow", "garden", "tree", "branch", "leaf", "flower",   "sunflower", "tulip", "daisy", "cactus", "grass", "pebble", "mud", "fire",
  "smoke", "shadow", "waterfall", "bridge", "seed", "lily",
  "bamboo", "glacier", "iceberg", "comet", "planet", "galaxy", "oasis",
  "lagoon", "cliff", "coral", "seaweed",
  // transport & places
  "car", "train", "airplane", "boat", "ship", "bicycle", "truck", "rocket",
  "helicopter", "tractor", "taxi", "bus", "submarine", "sailboat",
  "scooter", "skateboard", "canoe", "kayak", "school", "hospital", "church",
  "museum", "library", "bakery", "castle", "palace", "pyramid",
  "lighthouse", "windmill", "farm", "village", "airport", "circus",
  "playground", "zoo", "tunnel", "igloo", "cabin", "barn", "garage",
  "elevator", "balcony", "fireplace", "bench", "carousel", "trampoline",
  "aquarium", "cathedral", "stadium", "basketball",
  // characters
  "baby", "doctor", "teacher", "pirate", "queen", "king", "princess",
  "witch", "wizard", "ghost", "robot", "giant", "mermaid", "fairy", "angel",
  "cowboy", "astronaut", "sailor", "pilot", "snowman", "scarecrow",
  "puppet",
  // clothing
  "shirt", "dress", "pants", "jacket", "sweater", "scarf", "glove", "shoe",
  "pajamas",
];
