// Spanish dictionary — simple, concrete, phonetically distinct nouns.
// Curated: no homophones, no confusable near-pairs (enforced by tests/dictionaries.test.mjs).
export const WORDS_ES = [
  // animales
  "gato", "perro", "caballo", "cerdo", "conejo", "ratón",
  "ardilla", "zorro", "oso", "león", "tigre", "elefante", "jirafa", "cebra",
  "gorila", "canguro", "delfín", "ballena", "tiburón", "pulpo", "cangrejo",
  "gamba", "salmón", "atún", "sardina", "águila", "búho", "paloma", "gaviota",
  "ganso", "gallina", "pavo", "cisne", "flamenco", "pingüino", "tortuga",
  "lagarto", "serpiente", "rana", "caracol", "araña", "hormiga", "abeja",
  "avispa", "mariposa", "mosca", "escarabajo", "libélula",
  "luciérnaga", "erizo", "murciélago", "ciervo", "jabalí", "camello",   "nutria", "castor", "mapache", "panda", "koala", "dragón", "unicornio",
  "dinosaurio", "cocodrilo", "camaleón", "colibrí", "cigüeña", "cóndor",
  "búfalo", "calamar", "iguana", "jaguar", "leopardo", "lince", "lombriz",
  "mamut", "mariquita", "mofeta", "oruga", "ostra", "pájaro", "pantera",
  "pelícano", "periquito", "renacuajo", "reno", "rinoceronte", "ruiseñor",
  "salamandra", "tucán", "urraca", "hipopótamo", "langosta",
  // comida
  "pan", "queso", "leche", "huevo", "arroz", "sopa", "ensalada", "tomate",
  "cebolla", "zanahoria", "patata", "calabaza", "pepino", "lechuga", "maíz",
  "azúcar", "aceite", "mantequilla", "yogur", "helado", "galleta", "chocolate",
  "caramelo", "miel", "mermelada", "manzana", "pera", "plátano", "naranja",
  "limón", "sandía", "melón", "uva", "fresa", "cereza", "ciruela",
  "melocotón", "kiwi", "piña", "coco", "aguacate", "oliva",
  "almendra", "nuez", "avellana", "cacahuete", "café", "zumo", "agua",
  "tortilla", "paella", "empanada", "flan", "salchicha", "pollo", "pescado",
  "bizcocho", "tostada", "pastel", "pimiento", "brócoli", "berenjena",
  "espinaca", "canela", "chorizo", "garbanzo", "guisante",   "mandarina", "mostaza", "pistacho", "rábano", "remolacha",   // cuerpo
  "cabeza", "nariz", "boca", "oreja", "diente", "cuello", "hombro",
  "mano", "dedo", "pierna", "rodilla", "espalda", "corazón",
  "esqueleto", "barba", "bigote", "pestaña", "lengua",
  // casa y objetos
  "casa", "puerta", "ventana", "techo", "pared", "escalera",
  "cocina", "ducha", "espejo", "almohada", "manta", "sábana",   "silla", "mesa", "armario", "cajón", "lámpara", "vela", "llave",
  "cerradura", "timbre", "alfombra", "cortina", "cuadro", "reloj", "teléfono",
  "radio", "nevera", "horno", "sartén", "plato", "vaso",   "cuchara", "tenedor", "cuchillo", "botella", "jarra", "cubo", "escoba",
  "jabón", "toalla", "cepillo", "peine", "tijeras", "hilo", "botón",
  "bolsillo", "mochila", "bolsa", "regalo", "libro", "revista",
  "periódico", "carta", "sobre", "lápiz", "papel", "cuaderno", "pizarra",
  "chimenea", "colchón", "bombilla", "linterna", "candado", "cadena",
  "cuerda", "martillo", "clavo", "tornillo", "pala", "buzón", "paquete",
  "pincel", "imán", "plancha", "perfume", "medalla", "moneda",
  "billete", "tesoro", "corona", "mapa", "bandera", "brújula", "tienda",
  "faro", "jaula", "bolígrafo", "cesta", "esponja", "foto",   "grifo", "hamaca", "lavadora", "manguera", "marioneta", "máscara",
  "micrófono", "microscopio", "pañuelo", "paracaídas", "peluche", "persiana",
  "taladro", "tarjeta", "tetera", "ventilador", "xilófono", "biberón",
  "alcachofa", "altavoz", "anzuelo", "arándano", "azulejo", "bastón",
  "cacerola", "cafetera", "chaleco", "cojín", "cofre", "delantal",
  "despertador", "enchufe", "flotador", "maceta", "microondas",   "pinza", "regadera", "servilleta", "taburete", "toldo", "aspiradora",
  "ambulancia", "antena", "bambú", "barril", "burbuja", "cámara",
  "calendario", "canoa", "cartón",
  // naturaleza
  "sol", "luna", "estrella", "cielo", "nube", "lluvia", "nieve", "viento",
  "tormenta", "rayo", "trueno", "arcoíris", "niebla", "montaña",   "valle", "río", "lago", "mar", "océano", "playa", "arena", "isla",
  "volcán", "cueva", "bosque", "selva", "desierto", "pradera", "campo",
  "jardín", "árbol", "hoja", "tronco", "flor", "rosa", "margarita",
  "girasol", "tulipán", "cactus", "hierba", "piedra", "tierra", "polvo",
  "fuego", "ceniza", "sombra", "estanque", "cascada", "puente", "camino",
  "semilla", "nido", "pluma", "oasis", "galaxia", "cometa", "planeta",
  "césped", "coral", "glaciar", "helecho", "huerto", "huracán",
  "invernadero", "laberinto", "mármol", "pantano", "pétalo",
  "roble", "sendero", "trébol", "palmera", "colmena",
  // transporte y lugares
  "coche", "tren", "avión", "barco", "bicicleta", "autobús", "camión",
  "cohete", "globo", "ancla", "rueda", "semáforo", "castillo",
  "torre", "muralla", "escudo", "flecha", "molino", "aeropuerto",
  "biblioteca", "mercado", "escuela", "hospital", "iglesia", "museo",
  "teatro", "circo", "parque", "pueblo", "granja", "túnel", "taxi",
  "tractor", "trineo", "piscina", "palacio", "cabaña", "iglú", "pirámide",
  "estatua", "catedral", "carrusel", "columpio", "tobogán", "patio",
  "balcón", "fábrica", "garaje", "gimnasio", "monopatín", "mosaico",
  "noria", "quiosco", "rascacielos", "sótano", "terraza", "velero",
  "submarino", "helicóptero", "esquí", "pasaporte", "pedal", "pegatina",
  "salvavidas", "acuario", "grúa", "rastrillo",
  // personajes
  "payaso", "pirata", "reina", "bruja", "fantasma", "robot", "gigante",
  "sirena", "hada", "astronauta", "vaquero", "bombero", "médico", "maestro",
  "panadero", "cocinero", "jardinero", "bailarina", "piloto", "momia",
  "ángel", "bebé", "títere",
  // música y juegos
  "guitarra", "piano", "violín", "flauta", "tambor", "trompeta", "campana",
  "silbato", "acordeón", "arpa", "pelota", "muñeca", "juguete", "dominó",
  "casco", "armadura", "telescopio", "paraguas", "gafas", "anillo", "collar",
  "pulsera", "esmeralda", "diamante", "ajedrez", "clarinete", "gaita",
  "maracas", "saxofón", "trofeo", "trenza", "yunque", "toro", "cordero",
  // ropa
  "camisa", "pantalón", "falda", "vestido", "abrigo", "chaqueta",
  "jersey", "bufanda", "guante", "sombrero", "zapato", "sandalia",
  "calcetín", "cinturón", "corbata", "pijama",
];
